# The title of the website, if left empty this will default to the repository name
title: Projects

# Jekyll plugins that are supported by GitHub pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-redirect-from

# Also render the README to HTML even if there is an index.md
include:
  - README.md

# Exclude the `vendor` folder created by Travis
exclude:
  - vendor

# Use the Foundation For Public Code Jekyll theme
remote_theme: publiccodenet/jekyll-theme

# Display a table of contents on most pages
toc: true
